# Generated by Django 5.0.3 on 2024-04-28 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abugado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=2)),
                ('contact_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='AbugadoAcc',
            fields=[
                ('account_created', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('done', models.BooleanField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('abugado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abugado.abugado')),
            ],
        ),
    ]
