# Generated by Django 5.0.3 on 2024-04-30 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abugado',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=2)),
                ('contact_number', models.CharField(max_length=12)),
                ('abugado_acc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('done', models.BooleanField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('abugado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abugado.abugado')),
            ],
        ),
    ]
