# Generated by Django 5.0.3 on 2024-06-06 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abogado', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=1000)),
                ('fullLaw', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Summarizations',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('Summary', models.CharField(max_length=5000)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.law')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('abogado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abogado.abogado')),
                ('summary_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.summarizations')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryVerified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_date', models.DateField(auto_now_add=True)),
                ('abogado', models.ManyToManyField(to='abogado.abogado')),
                ('summary_id', models.ManyToManyField(to='wiki.summarizations')),
            ],
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('translation_id', models.AutoField(primary_key=True, serialize=False)),
                ('Bisaya_Translation', models.CharField(max_length=5000)),
                ('Tagalog_Translation', models.CharField(max_length=5000)),
                ('Waray_Translation', models.CharField(max_length=5000)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.law')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('abogado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abogado.abogado')),
                ('translation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.translations')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationVerified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_date', models.DateField(auto_now_add=True)),
                ('abogado', models.ManyToManyField(to='abogado.abogado')),
                ('translation_id', models.ManyToManyField(to='wiki.translations')),
            ],
        ),
    ]
