# Generated by Django 5.0.3 on 2024-05-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('abogado', 'Abogado'), ('manggagawa', 'Manggagawa'), ('admin', 'Admin')], max_length=20),
        ),
    ]
