# Generated by Django 5.0.3 on 2024-06-06 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abogado', '0002_initial'),
        ('authentication', '0001_initial'),
        ('manggagawa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='abogado',
            field=models.OneToOneField(blank=True, limit_choices_to={'user_type': 'abogado'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='abogado.abogado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manggagawa',
            field=models.OneToOneField(blank=True, limit_choices_to={'user_type': 'manggagawa'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='manggagawa.manggagawa'),
        ),
    ]
