# Generated by Django 5.0.3 on 2024-05-09 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abogado', '0001_initial'),
        ('authentication', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='abogado',
            field=models.OneToOneField(blank=True, limit_choices_to={'user_type': 'abogado'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='abogado.abogado'),
        ),
    ]
