# Generated by Django 5.0.2 on 2024-02-28 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=1000)),
                ('fullLaw', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Summarizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary', models.CharField(max_length=1000)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.law')),
            ],
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bisaya_Translation', models.CharField(max_length=1000)),
                ('Tagalog_Translation', models.CharField(max_length=1000)),
                ('Waray_Translation', models.CharField(max_length=1000)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.law')),
            ],
        ),
    ]
