# Generated by Django 5.0.3 on 2024-05-09 04:00

import abogado.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_initial', models.CharField(max_length=2)),
                ('birth_date', models.DateField(validators=[abogado.validators.validate_age])),
                ('gender', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField()),
                ('roll_signed_date', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('abogado_acc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='abogado_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('done', models.BooleanField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abogado.abogado')),
            ],
        ),
    ]
