# Generated by Django 5.0.3 on 2024-06-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abogado', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='cases_taken',
            field=models.IntegerField(default=0),
        ),
    ]
