# Generated by Django 5.0.3 on 2024-05-22 09:33

import django.db.models.deletion
import manggagawa.models
import manggagawa.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manggagawa',
            fields=[
                ('m_id', manggagawa.models.ManggagawaID(editable=False, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_initial', models.CharField(max_length=4)),
                ('birth_date', models.DateField(validators=[manggagawa.validators.validate_age])),
                ('gender', models.CharField(max_length=2)),
                ('contact_number', models.CharField(max_length=12)),
                ('trabaho', models.CharField(max_length=200)),
                ('manggagawa_acc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manggagawa_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('case_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('done', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='manggagawa.manggagawa')),
            ],
        ),
    ]
